{
  "legal/payment-terms.md": "Условия оплаты",
  "legal/privacy-policy.md": "Политика конфиденциальности",
  "legal/refund-policy.md": "Политика в отношении возврата денежных средств",
  "legal/rules-for-players.md": "Правила для игроков",
  "legal/user-agreement.md": "Пользовательское соглашение"
}
